CREATE TABLE `kd42696_ipr-projekt`.`entries` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `userID` INT NOT NULL ,
  `tanID` INT NOT NULL ,
  `vorname` LONGTEXT NOT NULL ,
  `nachname` LONGTEXT NOT NULL ,
  `geburtstag` LONGTEXT NOT NULL ,
  `wohnort` LONGTEXT NOT NULL ,
  `strasse` LONGTEXT NOT NULL ,
  `kennenUns` LONGTEXT NOT NULL ,
  `festnetz` LONGTEXT NOT NULL ,
  `handynummer` LONGTEXT NOT NULL ,
  `email` LONGTEXT NOT NULL ,
  `hobbies` LONGTEXT NOT NULL ,
  `berufswunsch` LONGTEXT NOT NULL ,
  `essen` LONGTEXT NOT NULL ,
  `insel` LONGTEXT NOT NULL ,
  `film` LONGTEXT NOT NULL ,
  `sport` LONGTEXT NOT NULL ,
  `charakter` LONGTEXT NOT NULL ,
  `tier` LONGTEXT NOT NULL ,
  `musik` LONGTEXT NOT NULL ,
  `game` LONGTEXT NOT NULL ,
  `alk` LONGTEXT NOT NULL ,
  `story` LONGTEXT NOT NULL ,
  `absturz` LONGTEXT NOT NULL ,
  `trinkspiel` LONGTEXT NOT NULL ,
  PRIMARY KEY (`id`),
  UNIQUE (`userID`),
  UNIQUE (`tanID`)) ENGINE = InnoDB;

  ALTER TABLE `entries` ADD FOREIGN KEY (`userID`) REFERENCES `user`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
  ALTER TABLE `entries` ADD FOREIGN KEY (`tanID`) REFERENCES `tans`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
